/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseUse: typeof import('./src/components/form/base-use/index.vue')['default']
    BaseUseNotJson: typeof import('./src/components/form/base-use-not-json/index.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseColls: typeof import('./src/components/form/use-colls/index.vue')['default']
  }
}
